<?php

namespace Ext\Func;

class FuncRef
{
    const VERSION = '22.3.25';

    public $function_reference = array(
        "Affecting PHP's Behaviour" => array(
            'APCu' => 'APC User Cache',
            'Componere',
            'Error Handling' => 'Error Handling and Logging',
            'FFI' => 'Foreign Function Interface',
            'OPcache',
            'Output Control' => 'Output Buffering Control',
            'PHP Options/Info' => 'PHP Options and Information',
            'phpdbg' => 'Interactive PHP Debugger',
            'runkit7',
            'uopz' => 'User Operations for Zend',
            'WinCache' => 'Windows Cache for PHP',
            'Xhprof' => 'Hierarchical Profiler',
            'Yac',
        ),
        'Audio Formats Manipulation' => array(
            'OpenAL' => 'OpenAL Audio Bindings',
        ),
        'Authentication Services' => array(
            'Radius',
        ),
        'Command Line Specific Extensions' => array(
            'Readline' => 'GNU Readline',
        ),
        'Compression and Archive Extensions' => array(
            'Bzip2',
            'LZF',
            'Phar',
            'Rar' => 'Rar Archiving',
            'Zip',
            'Zlib' => 'Zlib Compression',
        ),
        'Cryptography Extensions' => array(
            'CSPRNG',
            'Hash' => 'HASH Message Digest Framework',
            'Mcrypt',
            'Mhash',
            'OpenSSL',
            'Password Hashing',
            'Sodium',
        ),
        'Database Extensions' => array(
            'Abstraction Layers',
            'Vendor Specific Database Extensions',
        ),
        'Date and Time Related Extensions' => array(
            'Calendar',
            'Date/Time' => 'Date and Time',
            'HRTime' => 'High resolution timing',
        ),
        'File System Related Extensions' => array(
            'Direct IO',
            'Directories',
            'Fileinfo' => 'File Information',
            'Filesystem',
            'Inotify',
            'xattr',
            'xdiff',
        ),
        'Human Language and Character Encoding Support' => array(
            'Enchant' => 'Enchant spelling library',
            'Gender' => 'Determine gender of firstnames',
            'Gettext',
            'iconv',
            'intl' => 'Internationalization Functions',
            'Multibyte String',
            'Pspell',
            'Recode' => 'GNU Recode',
        ),
        'Image Processing and Generation' => array(
            'Exif' => 'Exchangeable image information',
            'GD' => 'Image Processing and GD',
            'Gmagick',
            'ImageMagick' => 'Image Processing (ImageMagick)',
        ),
        'Mail Related Extensions' => array(
            'IMAP' => 'IMAP, POP3 and NNTP',
            'Mail',
            'Mailparse',
        ),
        'Mathematical Extensions' => array(
            'BC Math' => 'BCMath Arbitrary Precision Mathematics',
            'GMP' => 'GNU Multiple Precision',
            'Math' => 'Mathematical Functions',
            'Trader' => 'Technical Analysis for Traders',
        ) ,
        'Non-Text MIME Output' => array(
            'FDF' => 'Forms Data Format',
            'GnuPG' => 'GNU Privacy Guard',
            'wkhtmltox',
            'PS' => 'PostScript document creation',
            'RpmInfo',
            'XLSWriter',
        ),
        'Process Control Extensions' => array(
            'Eio',
            'Ev',
            'Expect',
            'PCNTL' => 'Process Control',
            'POSIX',
            'Program execution' => 'System program execution',
            'parallel',
            'pthreads',
            'pht',
            'Semaphore' => 'Semaphore, Shared Memory and IPC',
            'Shared Memory',
            'Sync',
        )，
        'Other Basic Extensions' => array(
            'GeoIP' => 'Geo IP Location',
            'FANN' => 'FANN (Fast Artificial Neural Network)',
            'Igbinary',
            'JSON' => 'JavaScript Object Notation',
            'Lua',
            'LuaSandbox',
            'Misc.' => 'Miscellaneous Functions',
            'Seaslog',
            'SPL' => 'Standard PHP Library (SPL)',
            'Streams',
            'Swoole',
            'Tidy',
            'Tokenizer',
            'URLs',
            'V8js' => 'V8 Javascript Engine Integration',
            'Yaml' => 'YAML Data Serialization',
            'Yaf' => 'Yet Another Framework',
            'Yaconf',
            'Taint',
            'Data Structures',
            'var_representation',
        ),
        'Other Services' => array(
            'cURL' => 'Client URL Library',
            'Event',
            'FTP',
            'Gearman',
            'LDAP' => 'Lightweight Directory Access Protocol',
            'Memcache',
            'Memcached',
            'mqseries',
            'Network',
            'RRD' => 'RRDtool',
            'ScoutAPM',
            'SNMP',
            'Sockets',
            'SSH2' => 'Secure Shell2',
            'Stomp' => 'Stomp Client',
            'SVM' => 'Support Vector Machine',
            'SVN' => 'Subversion',
            'TCP' => 'TCP Wrappers',
            'Varnish',
            'YAZ',
            'OMQ messaging' => 'ZMQ',
            'ZooKeeper',
        ),
        'Search Engine Extensions' => array(
            'Solr' => 'Apache Solr',
        ),
        'Server Specific Extensions' => array(
            'Apache',
            'FastCGI Process Manager',
        ),
        'Session Extensions' => array(
            'Sessions' => 'Session Handling',
        ),
        'Text Processing' => array(
            'CommonMark',
            'Parle' => 'Parsing and lexing',
            'PCRE' => 'Regular Expressions (Perl-Compatible)',
            'ssdeep' => 'ssdeep Fuzzy Hashing',
            'Strings',
        ),
        'Variable and Type Related Extensions' => array(
            'Arrays',
            'Classes/Objects' => 'Class/Object Information',
            'Ctype' => 'Character type checking',
            'Filter' => 'Data Filtering',
            'Function Handling',
            'Reflection',
            'Variable handling',
        ),
        'Web Services' => array(
            'OAuth',
            'SOAP',
            'Yar' => 'Yet Another RPC Framework',
            'XML-RPC',
        ),
        'Windows Only Extensions' => array(
            'COM' => 'COM and .Net (Windows)',
            'win32service',
        ),
        'XML Manipulation' => array(
            'DOM' => 'Document Object Model',
            'libxml',
            'SimpleXML',
            'WDDX',
            'XMLDiff' => 'XML diff and merge',
            'XML Parser',
            'XMLReader',
            'XMLWriter',
            'XSL',
        ),
        'GUI Extensions' => array(
            'UI',
        ),
    );
}
