<?php

namespace Ext\Appendices;

class Alphabetical
{
    const VERSION = '22.3.25';

    public $alphabetical = array(
        'Apahce',
        'APCu',
        'Arrays',
        'BC Math',
        'Bzip2',
        'Calendar',
        'Classes/Objects',
        'CommonMark',
        'COM',
        'Componere',
        'CSPRNG',
        'Ctype',
        'CUBRID',
        'cURL',
        'Date/Time',
        'DBA',
        'dBase',
        'Direct IO',
        'Directories',
        'DOM',
        'Data Structures',
        'Eio',
        'Enchant',
        'Error Handling',
        'Ev',
        'Event',
        'Program execution',
        'Exif',
        'Expect',
        'FANN',
        'FDF',
        'FFI',
        'Fileinfo',
        'Filesystem',
        'Filter',
        'FastCGI Process Manager',
        'FTP',
        'Function Handling',
        'Gearman',
        'Gender',
        'GeoIP',
        'Gettext',
        'Gmagick',
        'GMP',
        'GnuPG',
        'Hash',
        'HRTime',
        'Firebird/InterBase',
        'IBM DB2',
        'iconv',
        'Igbinary',
        'GD',
        'ImageMagick',
        'IMAP',
        'PHP Options/Info',
        'Inotify',
        'intl',
        'JSON',
        'LDAP',
        'libxml',
        'Lua',
        'LuaSandbox',
        'LZF',
        'Mail',
        'Mailparse',
        'Math',
        'Multibyte String',
        'Mcrypt',
        'Memcache',
        'Memcached',
        'Mhash',
        'Misc.',
        'mqseries',
        'MySQL (Original)',
        'Mysql_xdevapi',
        'MySQLi',
        'Mysqlnd',
        'Network',
        'OAuth',
        'OCI8',
        'OPcache',
        'OpenAL',
        'OpenSSL',
        'Output Control',
        'parallel',
        'Parle',
        'Password Hashing',
        'PCNTL',
        'PCRE',
        'Password Hashing',
        'PCNTL',
        'PCRE',
        'PDO',
        'CUBRIO (PDO)',
        'MS SQL Server (PDO)',
        'Firebird (PDO)',
        'IBM (PDO)',
        'Informix (PDO)',
        'MySQL (PDO)',
        'Oracle (PDO)',
        'ODBC and DB2 (PDO)',
        'PostgreSQL (PDO)',
        'SQLite (PDO)',
        'MS SQL Server (PDO)',
        'PostgreSQL',
        'Phar',
        'phpdbg',
        'pht',
        'POSIX',
        'PS',
        'Pspell',
        'pthreads',
        'Radius',
        'Rar',
        'Readline',
        'Recode',
        'Reflection',
        'RpmInfo',
        'RRD',
        'runkit7',
        'ScoutAPM',
        'Seaslog',
        'Semaphore',
        'Sessions',
        'Shared Memory',
        'SimpleXML',
        'SNMP',
        'SOAP',
        'Sockets',
        'Sodium',
        'Solr',
        'SPL',
        'SQLite3',
        'SQLSRV',
        'ssdeep',
        'SSH2',
        'Stomp',
        'Streams',
        'Strings',
        'SVM',
        'SVN',
        'Swoole',
        'Sync',
        'Taint',
        'TCP',
        'Tidy',
        'Tokenizer',
        'Trader',
        'UI',
        'ODBC',
        'uopz',
        'URLs',
        'V8js',
        'Variable handling',
        'var_representation',
        'Varnish',
        'WDDX',
        'win32servie',
        'WinCache',
        'wkhtmltox',
        'xattr',
        'xdiff',
        'Xhprof',
        'XLSWriter',
        'XML Parser',
        'XMLDiff',
        'XMLReader',
        'XML-RPC',
        'XMLWrite',
        'XSL',
        'Yac',
        'Yaconf',
        'Yaf',
        'Yaml',
        'Yar',
        'YAZ',
        'Zip',
        'Zlib',
        'OMQ messaging',
        'ZooKeeper',
    );
}
