<?php

namespace Ext\Appendices;

class Membership
{
    const VERSION = '22.3.25';

    public $membership = array(
        'Core Extensions' => array(
            'Arrays',
            'Classes/Objects',
            'CSPRNG',
            'Date/Time',
            'Directories',
            'Error Handling',
            'Program execution',
            'Filesystem',
            'FastCGI Progress Manager',
            'Function Handling',
            'Hash',
            'PHP Options/Info',
            'JSON',
            'Mail',
            'Math',
            'Misc.',
            'Network',
            'OPcache',
            'Output Control',
            'Password Hashing',
            'PCRE',
            'Reflection',
            'SPL',
            'Streams',
            'Strings',
            'URLs',
            'Variable handling',
        ),
        'Bundled Extensions' => array(
            'Apache',
            'BC Math',
            'Calendar',
            'COM',
            'Ctype',
            'DBA',
            'Exif',
            'FFI',
            'Fileinfo',
            'Filter',
            'FTP',
            'HRTime',
            'iconv',
            'GD',
            'intl',
            'Multibyte String',
            'Mhash',
            'PCNTL',
            'PDO',
            'Phar',
            'phpdbg',
            'POSIX',
            'Semaphore',
            'Sessions',
            'Shared Memory',
            'Sockets',
            'SQLite3',
            'Tokenizer',
            'Zlib',
        ),
        'External Extensions' => array(
            'Bzip2',
            'cURL',
            'DOM',
            'Enchant',
            'Gettext',
            'GMP',
            'Igbinary',
            'IMAP',
            'LDAP',
            'libxml',
            'MySQLi',
            'Mysqlnd',
            'OCI8',
            'OpenSSL',
            'MS SQL Server (PDO)',
            'Firebird (PDO)',
            'MySQL (PDO)',
            'Oracle (PDO)',
            'ODBC and DB2 (PDO)',
            'PostgreSQL (PDO)',
            'pht',
            'Pspell',
            'Readline',
            'SimpleXML',
            'SNMP',
            'SOAP',
            'Sodium',
            'Tidy',
            'ODBC',
            'XML Parser',
            'XMLReader',
            'XMLWriter',
            'XSL',
            'Zip',
        ),
        'PECL Extensions' => array(
            'APCu',
            'CommonMark',
            'Componere',
            'CUBRID',
            'dBase',
            'Direct IO',
            'Data Structrues',
            'Eio',
            'Ev',
            'Event',
            'Expect',
            'FANN',
            'FDF',
            'Gearman',
            'Gender',
            'GeoIP',
            'Gmagick',
            'GnuPG',
            'Firebird/InterBase',
            'IBM DB2',
            'Igbinary',
            'ImageMagick',
            'Inotify',
            'Lua',
            'LuaSandbox',
            'LZF',
            'Mailparse',
            'Mcrypt',
            'Memcache',
            'Memcached',
            'mqseries',
            'MySQL (Original)',
            'Mysql_xdevapi',
            'OAuth',
            'OpenAL',
            'parallel',
            'Parle',
            'CUBRID (PDO)',
            'IBM (PDO)',
            'Informix (PDO)',
            'MS SQL Server (PDO)',
            'pht',
            'PS',
            'pthreads',
            'Radius',
            'Rar',
            'Recode',
            'RpmInfo',
            'RRD',
            'runkit7',
            'ScoutAPM',
            'Seaslog',
            'Solr',
            'SQLSRV',
            'ssdeep',
            'SSH2',
            'Stomp',
            'SVM',
            'SVN',
            'Swoole',
            'Sync',
            'Taint',
            'TCP',
            'Trader',
            'UI',
            'uopz',
            'V8js',
            'var_representation',
            'Varnish',
            'WDDX',
            'win32service',
            'WinCache',
            'wkhtmltox',
            'xattr',
            'xdiff',
            'Xhprof',
            'XLSWriter',
            'XMLDiff',
            'XML-RPC',
            'Yac',
            'Yaconf',
            'Yaf',
            'Yaml',
            'Yar',
            'YAZ',
            'OMQ messaging',
            'ZooKeeper',
        ),
    );
}
