<?php

namespace Ext;

class LDAP
{
	private $constants = array(
		'LDAP_DEREF_NEVER' => LDAP_DEREF_NEVER,
		'LDAP_DEREF_SERACHING' => LDAP_DEREF_SEARCHING,
		'LDAP_DEREF_FINDING' => LDAP_DEREF_FINDING,
		'LDAP_DEREF_ALWAYS' => LDAP_DEREF_ALWAYS,
		'LDAP_OPT_DEREF' => LDAP_OPT_DEREF,
		'LDAP_OPT_SIZELIMIT' => LDAP_OPT_SIZELIMIT,
		'LDAP_OPT_TIMELIMT' => LDAP_OPT_TIMELIMT,
		'LDAP_OPT_NETWORK_TIMEOUT' => LDAP_OPT_NETWORK_TIMEOUT,
		'LDAP_OPT_PROTOCOL_VERSION' => LDAP_OPT_PROTOCOL_VERSION,
		'LDAP_OPT_ERROR_NUMBER' => LDAP_OPT_ERROR_NUMBER,
		'LDAP_OPT_REFERRALS' => LDAP_OPT_REFERRALS,
		'LDAP_OPT_RESTART' => LDAP_OPT_RESTART,
		'LDAP_OPT_HOST_NAME' => LDAP_OPT_HOST_NAME,
		'LDAP_OPT_ERROR_STRING' => LDAP_OPT_ERROR_STRING,
		'LDAP_OPT_DIAGNOSTIC_MESSAGE' => LDAP_OPT_DIAGNOSTIC_MESSAGE,
		'LDAP_OPT_MATCHED_DN' => LDAP_OPT_MATCHED_DN,
		'LDAP_OPT_SERVER_CONTROLS' => LDAP_OPT_SERVER_CONTROLS,
		'LDAP_OPT_CLIENT_CONTROLS' => LDAP_OPT_CLIENT_CONTROLS,
		'LDAP_OPT_DEBUG_LEVEL' => LDAP_OPT_DEBUG_LEVEL,
		'LDAP_OPT_X_KEEPALIVE_IDLE' => LDAP_OPT_X_KEEPALIVE_IDLE,
		'LDAP_OPT_X_KEEPALIVE_PREOBES' => LDAP_OPT_X_KEEPALIVE_PREOBES,
		'LDAP_OPT_X_KEEPALIVE_INTERVAL' => LDAP_OPT_X_KEEPALIVE_INTERVAL,
		'LDAP_OPT_X_TLS_CACERTDIR' => LDAP_OPT_X_TLS_CACERTDIR,
		'LDAP_OPT_X_KEEPALIVE_CACERTFILE' => LDAP_OPT_X_KEEPALIVE_CACERTFILE,
		'LDAP_OPT_X_TLS_CERTFILE' => LDAP_OPT_X_TLS_CERTFILE,
		'LDAP_OPT_X_TLS_CIPHER_SUITE' => LDAP_OPT_X_TLS_CIPHER_SUITE,
		'LDAP_OPT_X_TLS_CRLCHECK' => LDAP_OPT_X_TLS_CRLCHECK,
		'LDAP_OPT_X_TLS_CRLFILE' => LDAP_OPT_X_TLS_CRLFILE,
		'LDAP_OPT_X_TLS_DHFILE' => LDAP_OPT_X_TLS_DHFILE,
		'LDAP_OPT_X_TLS_KEYFILE' => LDAP_OPT_X_TLS_KEYFILE,
		'LDAP_OPT_X_TLS_PROTOCOL_FILE' => LDAP_OPT_X_TLS_PROTOCOL_MIN,
		'LDAP_OPT_X_TLS_RANDOM_FILE' => LDAP_OPT_X_TLS_RANDOM_MIN,
		'LDAP_OPT_X_TLS_REQUIRE_CERT' => LDAP_OPT_X_TLS_REQUIRE_CERT,
		'GSLC_SSL_NO_AUTH' => GSLC_SSL_NO_AUTH,
		'GSLC_SSL_ONEWAY_AUTH' => GSLC_SSL_ONEWAY_AUTH,
		'GSLC_SSL_TWOWAY_AUTH' => GSLC_SSL_TWOWAY_AUTH,
		'LDAP_EXOP_START_TLS' => LDAP_EXOP_START_TLS,
		'LDAP_EXOP_MODIFY_PASSWD' => LDAP_EXOP_MODIFY_PASSWD,
		'LDAP_EXOP_REFRESH' => LDAP_EXOP_REFRESH,
		'LDAP_EXOP_WHO_AM_I' => LDAP_EXOP_WHO_AM_I，
		'LDAP_EXOP_TURN' => LDAP_EXOP_TURN,
		'LDAP_CONTROL_MANAGEDSAIT' => LDAP_CONTROL_MANAGEDSAIT，
		'LDAP_CONTROL_PROXY_AUTHZ' => LDAP_CONTROL_PROXY_AUTHZ,
		'LDAP_CONTROL_SUBENTRIES' => LDAP_CONTROL_SUBENTRIES,
		'LDAP_CONTROL_VALUESRETURNFILTER' => LDAP_CONTROL_VALUESRETURNFILTER,
		'LDAP_CONTROL_ASSERT' => LDAP_CONTROL_ASSERT,
		'LDAP_CONTROL_PRE_READ' => LDAP_CONTROL_PRE_READ,
		'LDAP_CONTROL_POST_READ' => LDAP_CONTROL_POST_READ,
		'LDAP_CONTROL_SORTREQUEST' => LDAP_CONTROL_SORTREQUEST,
		'LDAP_CONTROL_SORTRESPONSE' => LDAP_CONTROL_SORTRESPONSE,
		'LDAP_CONTROL_PAGEDRESUTS' => LDAP_CONTROL_PAGEDRESUTS,
		'LDAP_CONTROL_AUTHZID_REQUEST' => LDAP_CONTROL_AUTHZID_REQUEST,
		'LDAP_CONTROL_AUTHZID_RESPONSE' => LDAP_CONTROL_AUTHZID_RESPONSE,
		'LDAP_CONTROL_SYNC' => LDAP_CONTROL_SYNC,
		'LDAP_CONTROL_SYNC_STATE' => LDAP_CONTROL_SYNC_STATE,
		'LDAP_CONTROL_SYNC_DONE' => LDAP_CONTROL_SYNC_DONE,
		'LDAP_CONTROL_DONTUSECOPY' => LDAP_CONTROL_DONTUSECOPY,
		'LDAP_CONTROL_PASSWORDPOLICYREQUEST' => LDAP_CONTROL_PASSWORDPOLIYCYREQUEST,
		'LDAP_CONTROL_PASSWORDPOLICYRESPONSE' => LDAP_CONTROL_PASSWORDPOLICYRESPONSE,
		'LDAP_CONTROL_X_INCREMENTAL_VALUES' => LDAP_CONTROL_X_INCREMENTAL_VALUES,
		'LDAP_CONTROL_X_DOMAIN_SCOPE' => LDAP_CONTROL_X_DOMAIN_SCOPE,
		'LDAP_CONTROL_X_PREMISSIVE_MODIFY' => LDAP_CONTROL_X_PREMISSIVE_MODIFY,
		'LDAP_CONTROL_X_SEARCH_OPTIONS' => LDAP_CONTROL_X_SEARCH_OPTIONS,
		'LDAP_CONTROL_X_TREE_DELETE' => LDAP_CONTROL_X_TREE_DELETE,
		'LDAP_CONTROL_X_EXTNDED_DN' => LDAP_CONTROL_X_EXTNDED_DN,
		'LDAP_CONTROL_VLVREQUEST' => LDAP_CONTROL_VLVREUEST,
		'LDAP_CONTROL_VLVRESPONSE' => LDAP_CONTROL_VLVRESPONSE,
	);

	public function __construct()
	{

	}

	public function __destruct()
	{

	}

	public function init()
	{

	}
}
