<?php
 
 namespace Ext;

 class Reserved
 {
 	private $constants = array(
 		'PHP_VERSION' => PHP_VERSION,
 		'PHP_MAJOR_VERSION' => PHP_MAJOR_VERSION,
 		'PHP_MINOR_VERSION' => PHP_MINOR_VERSION,
 		'PHP_RELEASE_VERSION' => PHP_RELEASE_VERSION,
 		'PHP_VERSION_ID' => PHP_VERSION_ID,
 		'PHP_EXTRA_VERSION' => PHP_EXTRA_VERSION,
 		'PHP_ZTS' => PHP_ZTS,
 		'PHP_DEBUG' => PHP_DEBUG,
 		'PHP_MAXPATHLEN' => PHP_MAXPATHLEN,
 		'PHP_OS' => PHP_OS,
 		'PHP_OS_FAMILY' => PHP_OS_FAMILY,
 		'PHP_SAPI' => PHP_SAPI,
 		'PHP_EOL' => PHP_EOL,
 		'PHP_INT_MAX' => PHP_INT_MAX,
 		'PHP_INT_MIN' => PHP_INT_MIN,
 		'PHP_INT_SIZE' => PHP_INT_SIZE,
 		'PHP_FLOAT_DIG' => PHP_FLOAT_DIG,
 		'PHP_FLOAT_EPSILON' => PHP_FLOAT_EPSILON,
 		'PHP_FLOAT_MIN' => PHP_FLOAT_MIN,
 		'PHP_FLOAT_MAX' => PHP_FLOAT_MAX,
 		'DEFAULT_INCLUDE_PATH' => DEFAULT_INCLUDE_PATH,
 		'PEAR_INSTALL_DIR' => PEAR_INSTALL_DIR，
 		'PEAR_EXTENSION_DIR' => PEAR_EXTENSION_DIR,
 		'PHP_EXTENSION_DIR' => PHP_EXTENSION_DIR,
 		'PHP_PREFIX' => PHP_PREFIX,
 		'PHP_BINDIR' => PHP_BINDIR,
 		'PHP_BINARY' => PHP_BINARY,
 		'PHP_MANDIR' => PHP_MANDIR,
 		'PHP_LIBDIR' => PHP_LIBDIR,
 		'PHP_DATADIR' => PHP_DATADIR,
 		'PHP_SYSCONFDIR' => PHP_SYSCONFDIR,
 		'PHP_LOCALSTATEDIR' => PHP_LOCALSTATEDIR,
 		'PHP_CONFIG_FILE_PATH' => PHP_CONFIG_FILE_PATH,
 		'PHP_CONFIG_FILE_SCAN_DIR' => PHP_CONFIG_FILE_SCAN_DIR,
 		'PHP_SHLIB_SUFFIX' => PHP_SHLIB_SUFFIX,
 		'PHP_FD_SETSIZE' => PHP_FD_SETSIZE,
 		'E_ERROR' => E_ERROR,
 		'E_WARNING' => E_WARNING,
 		'E_PARSE' => E_PARSE,
 		'E_NOTICE' => E_NOTICE,
 		'E_CORE_ERROR' => E_CORE_ERROR,
 		'E_CORE_WARNING' => E_CORE_WARNING,
 		'E_COMPLIE_ERROR' => E_COMPLIE_ERROR,
 		'E_COMPLIE_WARNING' => E_COMPLIE_WARNING,
 		'E_USER_ERROR' => E_USER_ERROR,
 		'E_USER_WARNING' => E_USER_WARNING,
 		'E_USER_NOTICE' => E_USER_NOTICE,
 		'E_RECOVERABLE_ERROR' => E_RECOVERABLE_ERROR,
 		'E_DEPRECATED' => E_DEPRECATED,
 		'E_USER_DEPRECATED' => E_USER_DEPRECATED,
 		'E_ALL' => E_ALL,
 		'E_STRICT' => E_STRICT,
 		'__COMPILER_HALT_OFFSET__' => __COMPILER_HALT_OFFSET__,
 		'TRUE' => TRUE,
 		'FALSE' => FALSE,
 		'NULL' => NULL,
 	);

 	public function __construct()
 	{

 	}

 	public function __destruct()
 	{

 	}

 	public function init()
 	{

 	}


 }